### ISSUE TITLE
Get unexpected HTML Body when parsing the compressed "*.warc.gz" in CommonCrawl

### ISSUE THREAD

**Issue by jw8957** [toimik/WarcProtocol#6]
When using "toimik/WarcProtocol" to parse the "warc.gz" file from CommonCrawl. 
- For example one of the file: s3://commoncrawl/crawl-data/CC-MAIN-2023-14/segments/1679296948868.90/warc/CC-MAIN-20230328170730-20230328200730-00137.warc.gz

The HTML Body we parsed would got **Extra ending**. (One of the case can be seen in left part of snapshot).

But when we **Unzip** the "warc.gz" file first, then use "toimik/WarcProtocol" do the parse, we can get the **Correct one**.

Not sure if anyone met same issue, as CommonCrawl "warc.gz" files are widely used now.

![image](https://github.com/toimik/WarcProtocol/assets/4081007/8fc6e46d-a45c-4cff-b414-579a21a6e4d5)

**Comment by nurhafiz** [comment]
Thanks for submitting this issue. I'll take a look if time permits.
